"""
Метаданные колонок для отображения в таблицах Streamlit.
Хранятся в UI-слое, а не в модуле бизнес-логики.
"""

# Отображаемые названия колонок: техническое_имя → русский лейбл
COLUMN_LABELS: dict[str, str] = {
    "created_at": "Заказ создан",
    "shipment_date": "Дата отгрузки",
    "seller_name": "Магазин",
    "order_id_str": "Номер заказа",
    "offer_id": "Offer ID",
    "product_name": "Наименование",
    "order_status": "Статус заказа",
    "fulfillment_status": "Статус заказа 2",
    "payment_status": "Статус платежа",
    "quantity": "Количество",
    "supplier_name": "Отправлено от/из",
    "base_price_total": "Цена закупки",
    "ff_fee_total": "Цена упаковки",
    "socket_adapter_total": "Цена переходника",
    "price_with_margin": "Цена + маржа",
    "our_margin": "Маржа план ₽",
    "margin_fact_rub": "Маржа факт ₽",
    "margin_plan_pct": "Маржа план %",
    "margin_fact_pct": "Маржа факт %",
    "min_sell_price_total": "Минимальная цена",
    "expected_profit": "Ожидаемая прибыль",
    "sell_price": "Цена продажи",
    "bonus_points": "Субсидия ЯМ (справочно, в sell_price)",
    "promo_discounts": "Промо-расходы (наши баллы)",
    "diff_from_min_price": "Разница от мин. цены",
    "calc_commissions": "Расчётные комиссии",
    "market_services": "Комиссии (margin_report)",
    "fact_commissions": "Факт. комиссии (ЛК)",
    "income_after_fees": "Доход за вычетом комиссий",
    "profit": "Прибыль",
    "profit_vs_expected": "Разница Прибыли Факт/Ожид",
    "income_after_fees_promo": "Доход за вычетом комиссий и промо",
    "profit_no_promo": "Прибыль без учёта промо-расходов",
    "seller_cancel_penalty": "Штраф за отмену заказа",
    "late_ship_penalty": "Штраф за позднюю отгрузку",
    "payout_if_paid": "Нам перевели за заказ",
    "expected_payout": "Сумма выплаты (если нет даты, то ожидаемая)",
    "last_payment_date": "Дата выплаты",
    "actual_profit": "Фактическая прибыль",
}

# Порядок колонок в таблице заказов
DISPLAY_COLUMNS: list[str] = [
    "created_at",
    "shipment_date",
    "seller_name",
    "order_id_str",
    "offer_id",
    "product_name",
    "order_status",
    "fulfillment_status",
    "payment_status",
    "quantity",
    "supplier_name",
    "base_price_total",
    "ff_fee_total",
    "socket_adapter_total",
    "price_with_margin",
    "our_margin",
    "margin_fact_rub",
    "margin_plan_pct",
    "margin_fact_pct",
    "min_sell_price_total",
    "expected_profit",
    "sell_price",
    "bonus_points",
    "promo_discounts",
    "diff_from_min_price",
    "calc_commissions",
    "market_services",
    "fact_commissions",
    "income_after_fees",
    "profit",
    "profit_vs_expected",
    "income_after_fees_promo",
    "profit_no_promo",
    "seller_cancel_penalty",
    "late_ship_penalty",
    "payout_if_paid",
    "expected_payout",
    "last_payment_date",
    "actual_profit",
]
