"""
Метаданные колонок для отображения в таблицах Streamlit.
Хранятся в UI-слое, а не в модуле бизнес-логики.
"""

# Отображаемые названия колонок: техническое_имя → русский лейбл
COLUMN_LABELS: dict[str, str] = {
    "created_at": "Заказ создан",
    "shipment_date": "Дата отгрузки",
    "seller_name": "Магазин",
    "order_id_str": "Номер заказа",
    "offer_id": "Offer ID",
    "product_name": "Наименование",
    "order_status": "Статус заказа",
    "fulfillment_status": "Статус заказа 2",
    "payment_status": "Статус платежа",
    "quantity": "Количество",
    "supplier_name": "Отправлено от/из",
    "base_price_total": "Цена закупки",
    "base_price": "Цена закупки (WB)",
    "effective_purchase_total": "Факт. закупка",
    "supplier_price_fact": "Факт. закупка поставщика",
    "ff_fee_total": "Цена упаковки",
    "ff_fee": "Цена упаковки (WB)",
    "socket_adapter_total": "Цена переходника",
    "socket_adapter_fee": "Цена переходника (WB)",
    "custom_delivery_fee_total": "Доставка из Китая",
    "price_with_margin": "Цена + маржа",
    "our_margin": "Маржа план ₽",
    "margin_fact_rub": "Маржа факт ₽",
    "margin_plan_pct": "Маржа план % (от цены продажи)",
    "margin_fact_pct": "Маржа факт % (от цены продажи)",
    "margin_plan_on_cost_pct": "Маржа план % (от закупки)",
    "margin_fact_on_cost_pct": "Маржа факт % (от закупки)",
    "wb_profit_on_purchase_pct": "Маржа факт % (от факт. закупки WB)",
    "min_sell_price_total": "Минимальная цена",
    "final_price": "Минимальная цена WB",
    "min_price_multiplier": "Коэф. мин. цены WB",
    "expected_profit": "Ожидаемая прибыль",
    "sell_price_plan": "Плановая цена продажи WB",
    "report_sell_price": "Цена продажи по отчёту WB",
    "report_sell_price_cny": "Цена продажи по отчёту WB, ¥",
    "sell_price": "Цена продажи",
    "bonus_points": "Субсидия ЯМ (справочно, в sell_price)",
    "promo_discounts": "Промо-расходы (наши баллы)",
    "diff_from_min_price": "Разница от мин. цены",
    "category_fee": "Плановая комиссия WB",
    "report_commission": "Комиссия WB по отчёту",
    "report_commission_cny": "Комиссия WB по отчёту, ¥",
    "commission_fee_diff": "Расхождение комиссии WB",
    "acquiring_fee_plan": "Плановый эквайринг WB",
    "report_acquiring_fee": "Эквайринг WB по отчёту",
    "report_acquiring_fee_cny": "Эквайринг WB по отчёту, ¥",
    "delivery_fee_plan": "Плановая доставка WB",
    "report_delivery_fee": "Доставка WB по отчёту",
    "report_delivery_fee_cny": "Доставка WB по отчёту, ¥",
    "delivery_fee_diff": "Расхождение доставки WB",
    "calc_commissions": "Расчётные комиссии",
    "market_services": "Комиссии (margin_report)",
    "fact_commissions": "Факт. комиссии (ЛК)",
    "income_after_fees": "Доход за вычетом комиссий",
    "profit": "Прибыль",
    "profit_vs_expected": "Разница Прибыли Факт/Ожид",
    "income_after_fees_promo": "Доход за вычетом комиссий и промо",
    "profit_no_promo": "Прибыль без учёта промо-расходов",
    "seller_cancel_penalty": "Штраф за отмену заказа",
    "late_ship_penalty": "Штраф за позднюю отгрузку",
    "report_penalty": "Штрафы WB по отчёту",
    "report_penalty_cny": "Штрафы WB по отчёту, ¥",
    "report_compensation": "Компенсации WB по отчёту",
    "report_acceptance": "Приёмка WB по отчёту",
    "report_acceptance_cny": "Приёмка WB по отчёту, ¥",
    "report_storage_fee": "Хранение WB по отчёту",
    "report_storage_fee_cny": "Хранение WB по отчёту, ¥",
    "report_market_services_cny": "Комиссии WB по отчёту, ¥",
    "report_payout_cny": "Выплата WB по отчёту, ¥",
    "report_currency": "Валюта отчёта WB",
    "currency_rate": "Курс WB",
    "payout_if_paid": "Нам перевели за заказ",
    "expected_payout": "Сумма выплаты (если нет даты, то ожидаемая)",
    "last_payment_date": "Дата выплаты",
    "actual_profit": "Фактическая прибыль",
}

# ═══════════════════════════════════════════════════════════════════════════
# МегаМаркет
# ═══════════════════════════════════════════════════════════════════════════

MM_COLUMN_LABELS: dict[str, str] = {
    "created_at": "Заказ создан",
    "delivered_at": "Дата доставки",
    "seller_name": "Магазин",
    "order_id_str": "Номер заказа",
    "offer_id": "Offer ID",
    "product_name": "Наименование",
    "cdek_status": "Статус СДЭК",
    "item_status": "Статус позиции",
    "fulfillment_status": "Статус заказа",
    "payment_status": "Статус платежа",
    "channel": "Канал",
    "quantity": "Количество",
    "base_price_total": "Цена закупки",
    "effective_purchase_total": "Факт. закупка",
    "uses_fact_purchase_price": "Факт. цена?",
    "ff_fee_total": "Цена упаковки",
    "socket_adapter_total": "Цена переходника",
    "price_with_margin": "Цена + маржа",
    "our_margin": "Маржа план ₽",
    "margin_fact_rub": "Маржа факт ₽",
    "margin_plan_pct": "Маржа план % (от цены продажи)",
    "margin_fact_pct": "Маржа факт % (от цены продажи)",
    "margin_plan_on_cost_pct": "Маржа план % (от закупки)",
    "margin_fact_on_cost_pct": "Маржа факт % (от закупки)",
    "min_sell_price_total": "Минимальная цена",
    "expected_profit": "Ожидаемая прибыль",
    "sell_price": "Цена продажи (выручка)",
    "promo_discounts": "Промо-расходы (наши)",
    "bonus_from_mm": "Промо от ММ (справочно)",
    "diff_from_min_price": "Разница от мин. цены",
    "market_services": "Комиссии ММ",
    "delivery_commission": "Комиссия за доставку",
    "return_commission": "Комиссия за возврат",
    "cancellation_commission": "Комиссия за отмену",
    "return_delivery_cost": "Стоимость возврата СДЭК",
    "cdek_delivery_cost": "Стоимость доставки СДЭК",
    "delivery_cost": "Доставка (с покупателя)",
    "incentive_amount": "Оплата бонусами",
    "vat_on_incentive": "НДС на бонусы",
    "modifier_price": "Цена с модификаторами",
    "supplier_name": "Поставщик",
    "income_after_fees": "Доход за вычетом комиссий",
    "profit": "Прибыль",
    "profit_vs_expected": "Разница Прибыли Факт/Ожид",
    "income_after_fees_promo": "Доход за вычетом комиссий и промо",
    "profit_no_promo": "Прибыль без промо",
    "expected_payout": "Сумма выплаты",
    "payout_if_paid": "Нам перевели за заказ",
    "last_payment_date": "Дата выплаты",
    "deduction_date": "Дата списания",
    "actual_profit": "Фактическая прибыль",
    "our_costs": "Наши затраты",
}

MM_DISPLAY_COLUMNS: list[str] = [
    "created_at",
    "delivered_at",
    "seller_name",
    "order_id_str",
    "offer_id",
    "product_name",
    "channel",
    "cdek_status",
    "fulfillment_status",
    "payment_status",
    "quantity",
    "base_price_total",
    "effective_purchase_total",
    "ff_fee_total",
    "socket_adapter_total",
    "price_with_margin",
    "our_margin",
    "margin_fact_rub",
    "margin_plan_pct",
    "margin_fact_pct",
    "margin_plan_on_cost_pct",
    "margin_fact_on_cost_pct",
    "min_sell_price_total",
    "expected_profit",
    "sell_price",
    "promo_discounts",
    "bonus_from_mm",
    "diff_from_min_price",
    "incentive_amount",
    "vat_on_incentive",
    "market_services",
    "delivery_commission",
    "return_commission",
    "return_delivery_cost",
    "cdek_delivery_cost",
    "delivery_cost",
    "income_after_fees",
    "profit",
    "profit_vs_expected",
    "income_after_fees_promo",
    "profit_no_promo",
    "our_costs",
    "expected_payout",
    "payout_if_paid",
    "last_payment_date",
    "deduction_date",
    "actual_profit",
]

# ═══════════════════════════════════════════════════════════════════════════
# Сводная (общие колонки обоих МП)
# ═══════════════════════════════════════════════════════════════════════════

UNIFIED_COLUMNS: list[str] = [
    "marketplace",
    "order_id",
    "seller_name",
    "created_at",
    "fulfillment_status",
    "sell_price",
    "market_services",
    "expected_payout",
    "promo_discounts",
    "base_price_total",
    "our_costs",
    "effective_purchase_total",
    "profit",
    "profit_no_promo",
    "expected_profit",
    "margin_pct",
    "take_rate_pct",
]

UNIFIED_COLUMN_LABELS: dict[str, str] = {
    "marketplace": "Маркетплейс",
    "order_id": "Номер заказа",
    "seller_name": "Магазин",
    "created_at": "Заказ создан",
    "fulfillment_status": "Статус",
    "sell_price": "Цена продажи",
    "market_services": "Комиссии МП",
    "expected_payout": "Сумма выплаты",
    "promo_discounts": "Промо-расходы",
    "base_price_total": "Цена закупки",
    "our_costs": "Наши затраты",
    "effective_purchase_total": "Факт. закупка",
    "profit": "Прибыль",
    "profit_no_promo": "Прибыль без промо",
    "expected_profit": "Ожид. прибыль",
    "margin_pct": "Маржа %",
    "take_rate_pct": "Take rate %",
}

# Порядок колонок в таблице заказов
DISPLAY_COLUMNS: list[str] = [
    "created_at",
    "shipment_date",
    "seller_name",
    "order_id_str",
    "offer_id",
    "product_name",
    "order_status",
    "fulfillment_status",
    "payment_status",
    "quantity",
    "supplier_name",
    "base_price_total",
    "effective_purchase_total",
    "ff_fee_total",
    "socket_adapter_total",
    "custom_delivery_fee_total",
    "price_with_margin",
    "our_margin",
    "margin_fact_rub",
    "margin_plan_pct",
    "margin_fact_pct",
    "margin_plan_on_cost_pct",
    "margin_fact_on_cost_pct",
    "min_sell_price_total",
    "expected_profit",
    "sell_price",
    "bonus_points",
    "promo_discounts",
    "diff_from_min_price",
    "calc_commissions",
    "market_services",
    "fact_commissions",
    "income_after_fees",
    "profit",
    "profit_vs_expected",
    "income_after_fees_promo",
    "profit_no_promo",
    "seller_cancel_penalty",
    "late_ship_penalty",
    "payout_if_paid",
    "expected_payout",
    "last_payment_date",
    "actual_profit",
]
